---

- name: install netdata yum repo
  ansible.builtin.yum:
    name: "https://repo.netdata.cloud/repos/repoconfig/el/{{ ansible_distribution_major_version }}/x86_64/netdata-repo-2-2.noarch.rpm"
    state: present 

- name: install Netdata
  package:
    name: netdata
    state: present
